services:
  dockerdb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 'password'
      MARIADB_DATABASE: 'poster_generator'
      MARIADB_USER: 'poster_generator'
      MARIADB_PASSWORD: 'password'
    networks:
      - poster_generator_network
  poster_generator:
    build:
      context: .
    ports:
      - $LOCAL_PORT:80
    volumes:
      - type: volume
        source: json
        target: /poster_generator_json:rw
        volume:
          nocopy: true
    networks:
      - poster_generator_network
    tmpfs:
      - /tmp:rw
    environment:
      - IND=true
volumes:
  json:
networks:
  poster_generator_network:
    driver: bridge
