services:
  dockerdb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 'password'
      MARIADB_DATABASE: 'poster_generator'
      MARIADB_USER: 'poster_generator'
      MARIADB_PASSWORD: 'password'
    networks:
      - poster_generator_network
  poster_generator:
    build:
      context: .
    ports:
      - $LOCAL_PORT:8080
    volumes:
      - .:/var/www/html/:rw,delegated
    networks:
      - poster_generator_network
    tmpfs:
      - /tmp:rw
    environment:
      - IND=true

networks:
  poster_generator_network:
    driver: bridge
