#!/bin/bash

python_version=$(python3 --version | sed -e 's#Python ##')
VENV_DIR=$HOME/.poster_generator_test_suite_$python_version

if ! [[ -e requirements.txt ]]; then
	echo "requirements.txt not found"
	exit 1
fi

if ! command -v python3 2>/dev/null >/dev/null; then
	echo "python3 not found"
	exit 1
fi

requirements_hash=$(cat requirements.txt | md5sum | sed -e 's#\s.*##')

create_venv=0

if ! [[ -d $VENV_DIR ]]; then
	create_venv=1
fi

if ! [[ -e "$VENV_DIR/hash" ]]; then
	create_venv=1
fi

if [[ $create_venv -eq 1 ]]; then
	python3 -mvenv $VENV_DIR
fi

source $VENV_DIR/bin/activate

venv_hash=$(cat "$VENV_DIR/hash" 2>/dev/null)

if [[ $venv_hash != $requirements_hash ]]; then
	for install_me in $(cat requirements.txt); do
		pip install $install_me
	done

	echo "$requirements_hash" > "$VENV_DIR/hash"
fi

if [[ "$GITHUB_ACTIONS" = "true" ]]; then

	echo GITHUB_ACTION does exist
else
	echo GITHUB_ACTION does not exist
fi

echo -----------------------------------------------------------

# python3 poster_tests.py $*
# coverage run -p poster_tests.py
# coverage combine
# coverage report
