#!/bin/bash


if [[ -n $DB_NAME ]]; then
	DB_NAME="$DB_NAME"
else
	DB_NAME="db"
fi

python_version=$(python3 --version | sed -e 's#Python ##')
VENV_DIR=$HOME/.poster_generator_test_suite_$python_version

requirements=requirements.txt

if [[ ! -e $requirements ]]; then
	requirements="tests/$requirements"
fi

if ! [[ -e $requirements ]]; then
	echo "$requirements not found"
	exit 1
fi

if ! command -v python3 2>/dev/null >/dev/null; then
	echo "python3 not found"
	exit 1
fi

if [[ "$GITHUB_ACTIONS" != "true" ]]; then

	requirements_hash=$(cat $requirements | md5sum | sed -e 's#\s.*##')
	create_venv=0

	if ! [[ -d $VENV_DIR ]]; then
		create_venv=1
	fi

	if ! [[ -e "$VENV_DIR/hash" ]]; then
		create_venv=1
	fi

	if [[ $create_venv -eq 1 ]]; then
		python3 -mvenv $VENV_DIR
	fi

	source $VENV_DIR/bin/activate

	venv_hash=$(cat "$VENV_DIR/hash" 2>/dev/null)

	if [[ $venv_hash != $requirements_hash ]]; then
		for install_me in $(cat $requirements); do
			pip install $install_me
		done

		echo "$requirements_hash" > "$VENV_DIR/hash"
	fi

	echo Running Locally
else
	echo Running On GitHub Actions
fi

# sudo /etc/init.d/apache2 restart
# export DB_NAME=$DB_NAME

echo Running Frontend-Tests...

echo Run tests on Test-DB: ${DB_NAME}

if [[ "$GITHUB_ACTIONS" != "true" ]]; then
	# TODO:   doesnt seem to work correctly (local db poster_generator gets edited)
	sudo mariadb -e "DROP DATABASE IF EXISTS ${DB_NAME};"
	sudo mariadb -e "CREATE DATABASE IF NOT EXISTS ${DB_NAME};"
	sudo mariadb $DB_NAME < ./test_config2.sql
	sudo mariadb $DB_NAME < ./test_img.sql
	sudo mariadb -e "GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO 'poster_generator'@'%' IDENTIFIED BY 'password'; FLUSH PRIVILEGES;"
else
	mariadb -h 127.0.0.1 -P 3800 -u root -ppassword -e 'GRANT ALL PRIVILEGES ON *.* TO "poster_generator"@"%" IDENTIFIED BY "password"; FLUSH PRIVILEGES;'
	mariadb -h 127.0.0.1 -P 3800 -u poster_generator -ppassword -e "DROP DATABASE IF EXISTS ${DB_NAME};"
	mariadb -h 127.0.0.1 -P 3800 -u poster_generator -ppassword -e "CREATE DATABASE IF NOT EXISTS ${DB_NAME};"
	mariadb -h 127.0.0.1 -P 3800 -u poster_generator -ppassword $DB_NAME < ./test_config2.sql
	mariadb -h 127.0.0.1 -P 3800 -u poster_generator -ppassword $DB_NAME < ./test_img.sql
fi

python3 poster_tests.py $*
CODE=$?
#  $*

if [[ "$GITHUB_ACTIONS" != "true" ]]; then
	sudo mariadb-dump $DB_NAME > ./results_frontend_test.sql
	sudo mariadb -e "DROP DATABASE ${DB_NAME};"

	sudo mariadb -e "CREATE DATABASE IF NOT EXISTS poster_generator;"
	sudo mariadb poster_generator < ./test_config2.sql
	sudo mariadb poster_generator < ./test_img.sql
else
	mariadb-dump -h 127.0.0.1 -P 3800 -u poster_generator -ppassword $DB_NAME > ./results_frontend_test.sql
	mariadb -h 127.0.0.1 -P 3800 -u poster_generator -ppassword -e "DROP DATABASE ${DB_NAME};"
fi

# coverage run -p poster_tests.py
# coverage combine
# coverage report

echo End Frontend-Tests

exit $CODE
