#!/bin/bash

set -e

export DB_NAME="testDB"

echo Run tests on Test-DB: ${DB_NAME}

sudo mariadb -e "CREATE DATABASE IF NOT EXISTS ${DB_NAME};"
sudo mariadb $DB_NAME < ./tests/test_config2.sql
sudo mariadb -e "GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO 'poster_generator'@'localhost' IDENTIFIED BY 'password'; FLUSH PRIVILEGES;"

php testing.php $DB_NAME

sudo mariadb-dump $DB_NAME > ./tests/post_test.sql
sudo mariadb -e "DROP DATABASE ${DB_NAME};"


php -r 'foreach(get_defined_functions()["internal"] as $i) {echo $i . "\n";};' > ./tests/php_build_in_func
for i in `cat ./tests/files_to_test`
do
    echo $i
    python3 ./tests/coverage.py $i ./testing.php
done
