#!/bin/bash

set -e

export DB_NAME="testDB"

sudo mariadb -e "CREATE DATABASE IF NOT EXISTS ${DB_NAME};"
sudo mariadb $DB_NAME < ./tests/test_config2.sql

# TODO: unsave
sudo mariadb -e "CREATE USER poster_generator@localhost IDENTIFIED BY 'password';"

echo User:
sudo mariadb -e "select user(),current_user();"

sudo mariadb -e "GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO 'poster_generator'@'localhost' IDENTIFIED BY 'password'; FLUSH PRIVILEGES;"

echo User:
sudo mariadb -e "select user(),current_user();"

echo Running Backend-Tests...

echo Run tests on Test-DB: ${DB_NAME}

php testing.php $DB_NAME

sudo mariadb-dump $DB_NAME > ./tests/results_backend_test.sql
sudo mariadb -e "DROP DATABASE ${DB_NAME};"


php -r 'foreach(get_defined_functions()["internal"] as $i) {echo $i . "\n";};' > ./tests/php_build_in_func

for i in __halt_compiler abstract and array as break callable case catch class clone const continue declare default die do echo else elseif empty enddeclare endfor endforeach endif endswitch endwhile eval exit extends final for foreach function global goto if implements include include_once instanceof insteadof interface isset list namespace new or print private protected public require require_once return static switch throw trait try unset use var while xor
do
 echo $i >> ./tests/php_build_in_func
done

# for i in `cat ./tests/files_to_test`
# do
#     echo --- ${i}
#     python3 ./tests/coverage.py $i ./testing.php | sed 's/^/- /'
# done

cd tests; ./run_tests $DB_NAME; cd ..

echo --- Backend Coverage ---
python3 ./tests/coverage.py ./testing.php 2 0 0

echo --- Frontend Coverage ---
echo -
