#!/bin/bash

set -e

if [[ -z $DB_PORT ]]; then
	DB_PORT=3800
fi

is_in_docker() {
	# Methode 1: Check nach /.dockerenv (Datei existiert meist nur in Docker)
	if [ -f "/.dockerenv" ]; then
		return 0
	fi

	# Methode 2: cgroup enthält "docker" oder "kubepods"
	if grep -qE 'docker|kubepods' /proc/1/cgroup 2>/dev/null; then
		return 0
	fi

	return 1
}

if is_in_docker; then
	echo "This test script cannot be run inside of a docker-container (for now)"
	exit 1
fi

# TODO:   doesnt seem to work on other than poster_generator
export DB_NAME="poster_generator"

if [[ "$GITHUB_ACTIONS" != "true" ]]; then
	if is_in_docker; then
		mariadb -hdockerdb -uroot -ppassword -e "GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO 'poster_generator'@'%' IDENTIFIED BY 'password'; FLUSH PRIVILEGES;"
		mariadb -hdockerdb -uroot -ppassword -e "CREATE DATABASE IF NOT EXISTS ${DB_NAME};"
		mariadb -hdockerdb -uroot -ppassword $DB_NAME < ./tests/test_config2.sql
		mariadb -hdockerdb -uroot -ppassword $DB_NAME < ./tests/test_img.sql
	else
		sudo mariadb -e "GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO 'poster_generator'@'%' IDENTIFIED BY 'password'; FLUSH PRIVILEGES;"
		sudo mariadb -e "CREATE DATABASE IF NOT EXISTS ${DB_NAME};"
		sudo mariadb $DB_NAME < ./tests/test_config2.sql
		sudo mariadb $DB_NAME < ./tests/test_img.sql

		export root_path="/ScivoWall";
	fi
else
	mariadb -h 127.0.0.1 -P $DB_PORT -u root -ppassword -e 'GRANT ALL PRIVILEGES ON *.* TO "poster_generator"@"%" IDENTIFIED BY "password"; FLUSH PRIVILEGES;'
	mariadb -h 127.0.0.1 -P $DB_PORT -u poster_generator -ppassword -e "CREATE DATABASE IF NOT EXISTS ${DB_NAME};"
	mariadb -h 127.0.0.1 -P $DB_PORT -u poster_generator -ppassword $DB_NAME < ./tests/test_config2.sql
	mariadb -h 127.0.0.1 -P $DB_PORT -u poster_generator -ppassword $DB_NAME < ./tests/test_img.sql
fi

echo Running Backend-Tests...

echo Run tests on Test-DB: ${DB_NAME}

php testing.php $DB_NAME
CODE=$?

if [[ "$GITHUB_ACTIONS" != "true" ]]; then
	if is_in_docker; then
		mariadb-dump -hdockerdb -uroot -ppassword  $DB_NAME > ./tests/results_backend_test.sql
		mariadb -hdockerdb -uroot -ppassword  -e "DROP DATABASE ${DB_NAME};"
	else
		sudo mariadb-dump $DB_NAME > ./tests/results_backend_test.sql
		sudo mariadb -e "DROP DATABASE ${DB_NAME};"
	fi
else
	mariadb-dump -h 127.0.0.1 -P $DB_PORT -u poster_generator -ppassword $DB_NAME > ./tests/results_backend_test.sql
	mariadb -h 127.0.0.1 -P $DB_PORT -u poster_generator -ppassword -e "DROP DATABASE ${DB_NAME};"
fi

php -r 'foreach(get_defined_functions()["internal"] as $i) {echo $i . "\n";};' > ./tests/php_build_in_func

for i in __halt_compiler abstract and array as break callable case catch class clone const continue declare default die do echo else elseif empty enddeclare endfor endforeach endif endswitch endwhile eval exit extends final for foreach function global goto if implements include include_once instanceof insteadof interface isset list namespace new or print private protected public require require_once return static switch throw trait try unset use var while xor
do
 echo $i >> ./tests/php_build_in_func
done

# for i in `cat ./tests/files_to_test`
# do
#     echo --- ${i}
#     python3 ./tests/coverage.py $i ./testing.php | sed 's/^/- /'
# done

cd tests
export DB_NAME
./run_tests $*
CODE=$?
cd ..

echo --- Backend Coverage ---
# python3 ./tests/coverage.py ./testing.php 2 0 0

echo --- Frontend Coverage ---
echo -

exit $CODE
